version: "3.8"

services:
  qbase:
    container_name: qbase
    image: postgres:13
    ports:
      - 15432:5432
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    tmpfs:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Cyzgiv12
