#!/bin/bash
schemaspy \
    -t pgsql \
    -host localhost:15432 \
    -db qbase \
    -s public \
    -u qbase \
    -p Jellux37 \
    -o /tmp/qbase-schema \
    -dp postgresql-42.2.5.jar

current="$(dirname $(readlink -f $0))"
pushd /tmp/qbase-schema/diagrams/summary/
dot -Tsvg:cairo -o "${current}/schema.svg" relationships.real.large.dot
popd
